---
suppress-bibliography: true
---


# 결론 {#chapter-11-conclusion}

이 마지막 장에서 책이 마무리됩니다.
이전 10개 장에서 논의한 내용을 먼저 요약한 다음, 세 가지 조언을 제공하고 우리가 다룬 관련 주제를 추가로 탐색할 수 있는 몇 가지 자료를 제공할 것입니다.
마지막으로 질문, 의견 또는 공유할 새로운 명령줄 도구가 있는 경우 저에게 연락할 수 있는 몇 가지 방법을 제공합니다.


## 요약해 봅시다

이 책은 데이터 과학을 수행하기 위해 명령줄을 사용하는 것의 강력함을 탐구했습니다.
이 비교적 젊은 분야가 제기하는 과제를 이처럼 오랜 시간 검증된 기술로 해결할 수 있다는 것은 흥미로운 관찰입니다.
이제 명령줄이 무엇을 할 수 있는지 알게 되셨기를 바랍니다.
많은 명령줄 도구는 데이터 과학을 포괄하는 다양한 작업에 적합한 모든 종류의 가능성을 제공합니다.

데이터 과학에 대한 많은 정의가 있습니다.
[1장](#chapter-1-introduction)에서는 Mason과 Wiggins가 정의한 OSEMN 모델을 소개했습니다. 이는 매우 구체적인 작업으로 변환되는 매우 실용적인 모델이기 때문입니다.
약어 OSEMN은 데이터 획득, 정제, 탐색, 모델링 및 해석을 의미합니다. [1장](#chapter-1-introduction)에서는 또한 이러한 데이터 과학 작업을 수행하는 데 명령줄이 매우 적합한 이유를 설명했습니다.

[2장](#chapter-2-getting-started)에서는 이 책에서 사용된 모든 도구를 얻는 방법을 설명했습니다. [2장](#chapter-2-getting-started)에서는 또한 명령줄의 필수 도구와 개념에 대한 소개를 제공했습니다.

네 가지 OSEMN 모델 장에서는 명령줄을 사용하여 이러한 실제 작업을 수행하는 데 중점을 두었습니다.
솔직히 말해서 컴퓨터는 물론이고 명령줄도 여기서는 거의 쓸모가 없기 때문에 다섯 번째 단계인 데이터 해석에 대한 장을 할애하지 않았습니다.
그러나 이 주제에 대한 추가 자료에 대한 몇 가지 포인터를 제공했습니다.

네 개의 막간 장에서는 명령줄에서 데이터 과학을 수행하는 것에 대한 더 광범위한 주제, 즉 특정 단계에 국한되지 않는 주제를 살펴보았습니다.
[4장](#chapter-4-creating-command-line-tools)에서는 한 줄짜리 코드와 기존 코드를 재사용 가능한 명령줄 도구로 바꾸는 방법을 설명했습니다.
[6장](#chapter-6-project-management-with-make)에서는 `make`라는 도구를 사용하여 데이터 워크플로를 관리하는 방법을 설명했습니다.
[8장](#chapter-8-parallel-pipelines)에서는 GNU Parallel을 사용하여 일반적인 명령줄 도구와 파이프라인을 병렬로 실행하는 방법을 보여주었습니다.
[10장](#chapter-10-polyglot-data-science)에서는 명령줄이 진공 상태에 존재하지 않고 다른 프로그래밍 언어와 환경에서 활용될 수 있음을 보여주었습니다.
이러한 막간 장에서 논의된 주제는 데이터 워크플로의 어느 시점에서든 적용할 수 있습니다.

데이터 과학을 수행하는 데 사용할 수 있고 관련된 모든 명령줄 도구를 보여주는 것은 불가능합니다.
새로운 도구는 매일 만들어집니다.
이제 이해하셨겠지만 이 책은 도구의 전체 목록을 제공하는 것보다 명령줄을 사용하는 아이디어에 관한 것입니다.


## 세 가지 조언

아마도 이 장들을 읽고 코드 예제를 따라 하는 데 꽤 많은 시간을 할애했을 것입니다.
이 투자에 대한 수익을 극대화하고 데이터 과학 워크플로에 명령줄을 계속 통합할 가능성을 높이기 위해 세 가지 조언을 드리고자 합니다. (1) 인내심을 가지십시오. (2) 창의적이 되십시오. (3) 실용적이 되십시오. 다음 세 하위 섹션에서는 각 조언에 대해 자세히 설명합니다.


### 인내심을 가지십시오

제가 드릴 수 있는 첫 번째 조언은 인내심을 가지라는 것입니다.
명령줄에서 데이터를 사용하는 것은 프로그래밍 언어를 사용하는 것과 다르므로 다른 사고방식이 필요합니다.

또한 명령줄 도구 자체에는 단점과 불일치가 없는 것이 아닙니다.
이는 부분적으로 수십 년에 걸쳐 많은 다른 사람들이 개발했기 때문입니다.
정신을 혼미하게 만드는 옵션에 대해 어찌할 바를 모를 경우 --help, `man`, `tldr` 또는 즐겨 사용하는 검색 엔진을 사용하여 자세히 알아보는 것을 잊지 마십시오.

그럼에도 불구하고 특히 처음에는 답답한 경험이 될 수 있습니다.
저를 믿으십시오. 명령줄과 해당 도구를 사용하는 연습을 하면 더 능숙해질 것입니다.
명령줄은 수십 년 동안 사용되어 왔으며 앞으로도 오랫동안 사용될 것입니다.
가치 있는 투자입니다.


### 창의적이 되십시오

두 번째 관련 조언은 창의적이 되라는 것입니다.
명령줄은 매우 유연합니다.
명령줄 도구를 결합하면 생각보다 더 많은 것을 달성할 수 있습니다.

프로그래밍 언어로 즉시 돌아가지 않도록 권장합니다.
그리고 프로그래밍 언어를 사용해야 하는 경우 코드를 어떤 방식으로든 일반화하거나 재사용할 수 있는지 생각해 보십시오.
그렇다면 [4장](#chapter-4-creating-command-line-tools)에서 논의한 단계를 사용하여 해당 코드로 자신만의 명령줄 도구를 만드는 것을 고려하십시오.
도구가 다른 사람에게 유익할 수 있다고 생각되면 오픈 소스로 만들어 한 단계 더 나아갈 수도 있습니다.
명령줄에서 수행하는 방법을 알고 있지만 작업 중인 기본 프로그래밍 언어 또는 환경의 편안함을 떠나고 싶지 않은 단계가 있을 수 있습니다.
아마도 [10장](#chapter-10-polyglot-data-science)에 나열된 접근 방식 중 하나를 사용할 수 있을 것입니다.


### 실용적이 되십시오

세 번째 조언은 실용적이 되라는 것입니다.
실용적인 것은 창의적인 것과 관련이 있지만 별도의 설명이 필요합니다.
이전 하위 섹션에서는 프로그래밍 언어로 즉시 돌아가지 말아야 한다고 언급했습니다.
물론 명령줄에는 한계가 있습니다.
이 책 전체에서 명령줄은 데이터 과학을 수행하는 보조적인 접근 방식으로 간주되어야 한다고 강조했습니다.

명령줄에서 데이터 과학을 수행하기 위한 네 가지 단계를 논의했습니다.
실제로 명령줄의 적용 가능성은 4단계보다 1단계에서 더 높습니다.
당면한 작업에 가장 적합한 접근 방식을 사용해야 합니다.
그리고 워크플로의 어느 시점에서든 접근 방식을 혼합하고 일치시키는 것은 완벽하게 괜찮습니다.
[10장](#chapter-10-polyglot-data-science)에서 보여주었듯이 명령줄은 다른 접근 방식, 프로그래밍 언어 및 통계 환경과 통합되는 데 훌륭합니다.
각 접근 방식에는 특정 장단점이 있으며 명령줄에 능숙해지는 것의 일부는 어떤 것을 언제 사용해야 하는지 배우는 것입니다.

결론적으로 인내심 있고 창의적이며 실용적이라면 명령줄을 통해 더 효율적이고 생산적인 데이터 과학자가 될 수 있습니다.


## 다음 단계는 무엇입니까?

이 책은 명령줄과 데이터 과학의 교차점에 있으므로 많은 관련 주제가 간략하게만 다루어졌습니다.
이제 이러한 주제를 추가로 탐색하는 것은 사용자에게 달려 있습니다.
다음 하위 섹션에서는 참조할 주제 목록과 제안된 자료를 제공합니다.


## 명령줄

- William E. Shotts, Jr.의 *The Linux Command Line: A Complete Introduction, 2nd Edition* (No Starch Press, 2019)
- Jerry Peek, Shelley Powers, Tim O'Reilly, Mike Loukides의 *Unix Power Tools, 3rd Edition* (O'Reilly Media, 2002)
- Arnold Robbins, Elbert Hannah, Linda Lamb의 *Learning the Vi and Vim Editors, 7th Edition* (O'Reilly Media, 2008)


### 셸 프로그래밍

- Arnold Robbins와 Nelson H.F. Beebe의 *Classic Shell Scripting* (O'Reilly Media, 2005)
- Dave Taylor와 Brandon Perry의 *Wicked Cool Shell Scripts, 2nd Edition* (No Starch Press, 2017)
- Carl Albing JP Vossen의 *Bash Cookbook* (O'Reilly Media, 2018)


### Python, R, SQL

- Zed A. Shaw의 *Learn Python 3 the Hard Way* (Addison-Wesley Professional, 2017)
- Wes McKinney의 *Python for Data Analysis, 2nd Edition* (O'Reilly Media, 2017)
- Joel Grus의 *Data Science from Scratch, 2nd Edition* (O'Reilly Media, 2019)
- Garrett Grolemund와 Hadley Wickham의 *R for Data Science* (O'Reilly Media, 2016)
- Jared Lander의 *R for Everyone, 2nd edition* (Addison-Wesley Professional, 2017)
- Ben Forta의 *Sams Teach Yourself SQL in 10 Minutes a Day, 5th Edition* (Sams, 2020)


### API

- Matthew A. Russell과 Mikhail Klassen의 *Mining the Social Web, 3rd Edition* (O'Reilly Media, 2019)
- Pete Warden의 *Data Source Handbook* (O'Reilly Media, 2011)


### 기계 학습

- Sebastian Raschka와 Vahid Mirjalili의 *Python Machine Learning, 3rd Edition* (Packt Publishing, 2019)
- Christopher M. Bishop의 *Pattern Recognition and Machine Learning* (Springer, 2006)
- David MacKay의 *Information Theory, Inference, and Learning Algorithms* (Cambridge University Press, 2003)


## 연락하기

이 책은 명령줄과 수많은 도구를 만든 많은 사람들 없이는 불가능했을 것입니다.
데이터 과학을 위한 현재 명령줄 도구 생태계는 커뮤니티의 노력이라고 해도 과언이 아닙니다.
저는 사용 가능한 많은 명령줄 도구 중 일부만 보여줄 수 있었습니다.
새로운 도구는 매일 만들어지며 언젠가는 직접 만들 수도 있습니다.
이 경우 귀하의 의견을 듣고 싶습니다.
질문, 의견 또는 제안이 있을 때마다 저에게 연락해 주시면 감사하겠습니다.
연락할 수 있는 몇 가지 방법이 있습니다.

- 이메일: <jeroen@jeroenjanssens.com>
- 트위터: [\@jeroenhjanssens](https://twitter.com/jeroenhjanssens/)
- 책 웹사이트: <https://datascienceatthecommandline.com/>
- 책 GitHub 저장소: <https://github.com/jeroenjanssens/data-science-at-the-command-line>

감사합니다.
