---
suppress-bibliography: true
---


# 결론 {#chapter-11-conclusion}

이 마지막 장으로 책을 마무리하겠습니다.
먼저 이전 10개 장에서 논의한 내용을 요약하고, 여러분께 세 가지 조언과 함께 우리가 다루었던 관련 주제들을 더 깊이 탐구할 수 있는 자료들을 제안해 드리겠습니다.
마지막으로 질문이나 의견이 있거나 공유하고 싶은 새로운 커맨드 라인 도구가 있는 경우에 대비하여 저와 연락할 수 있는 몇 가지 방법을 알려드립니다.


## 요약해 봅시다

이 책은 데이터 과학을 수행하는 데 있어 커맨드 라인을 사용하는 힘을 탐구했습니다.
상대적으로 젊은 분야인 데이터 과학이 직면한 과제들을 이처럼 오랜 시간 검증된 기술로 해결할 수 있다는 것은 매우 흥미로운 발견이라고 생각합니다.
이제 여러분이 커맨드 라인으로 무엇을 할 수 있는지 이해하셨기를 바랍니다.
수많은 커맨드 라인 도구들은 데이터 과학을 구성하는 다양한 작업들에 적합한 온갖 가능성을 제공합니다.

데이터 과학에 대한 많은 정의가 존재합니다.
[1장](#chapter-1-introduction)에서 저는 Mason과 Wiggins이 정의한 OSEMN 모델을 소개했습니다. 왜냐하면 매우 구체적인 작업들로 연결되는 아주 실용적인 모델이기 때문입니다.
OSEMN은 데이터 수집(obtaining), 정제(scrubbing), 탐색(exploring), 모델링(modeling), 해석(interpreting)의 약자입니다. 또한 [1장](#chapter-1-introduction)에서는 왜 커맨드 라인이 이러한 데이터 과학 작업들에 매우 적합한지도 설명했습니다.

[2장](#chapter-2-getting-started)에서는 이 책에서 사용된 모든 도구를 얻는 방법을 설명했습니다. 또한 [2장](#chapter-2-getting-started)에서는 커맨드 라인의 필수적인 도구와 개념들에 대한 소개도 제공했습니다.

네 개의 OSEMN 모델 장에서는 커맨드 라인을 사용하여 실용적인 작업들을 수행하는 데 집중했습니다.
다섯 번째 단계인 데이터 해석(interpreting data)에 대해서는 별도의 장을 할애하지 않았습니다. 솔직히 말해서 커맨드 라인은커녕 컴퓨터조차도 이 단계에서는 거의 도움이 되지 않기 때문입니다.
하지만 이 주제에 대해 더 읽어볼 만한 몇 가지 포인터를 제공했습니다.

네 개의 중간 막(intermezzo) 장에서는 커맨드 라인에서 데이터 과학을 수행하는 데 있어 어느 한 단계에만 국한되지 않는 더 넓은 주제들을 살펴보았습니다.
[4장](#chapter-4-creating-command-line-tools)에서는 한 줄짜리 명령어(one-liners)와 기존 코드를 재사용 가능한 커맨드 라인 도구로 바꾸는 방법을 설명했습니다.
[6장](#chapter-6-project-management-with-make)에서는 `make`라는 도구를 사용하여 데이터 워크플로우를 관리하는 방법을 설명했습니다.
[8장](#chapter-8-parallel-pipelines)에서는 일반적인 커맨드 라인 도구와 파이프라인을 GNU Parallel을 사용하여 병렬로 실행하는 방법을 보여주었습니다.
[10장](#chapter-10-polyglot-data-science)에서는 커맨드 라인이 진공 상태에서 존재하는 것이 아니라 다른 프로그래밍 언어나 환경에서도 활용될 수 있음을 보여주었습니다.
이 중간 막 장들에서 다룬 주제들은 여러분의 데이터 워크플로우 어느 지점에서도 적용될 수 있습니다.

데이터 과학을 수행하는 데 사용할 수 있고 관련이 있는 모든 커맨드 라인 도구를 보여주는 것은 불가능합니다.
새로운 도구들이 매일 만들어지고 있기 때문입니다.
이제 이해하셨겠지만, 이 책은 도구의 전수 조사를 제공하기보다는 커맨드 라인을 사용한다는 아이디어 자체에 더 중점을 두었습니다.


## 세 가지 조언

여러분은 아마도 이 장들을 읽고 코드 예제들을 따라 하는 데 꽤 많은 시간을 보냈을 것입니다.
이러한 투자의 효과를 극대화하고 여러분이 데이터 과학 워크플로우에 커맨드 라인을 계속해서 통합할 가능성을 높이기 위해, 저는 여러분께 세 가지 조언을 드리고 싶습니다: (1) 인내심을 갖고(be patient), (2) 창의적이며(be creative), (3) 실용적이 되십시오(be practical). 다음 세 개의 하위 섹션에서 각 조언에 대해 자세히 설명하겠습니다.


### 인내심을 가지십시오

제가 드릴 수 있는 첫 번째 조언은 인내심을 가지라는 것입니다.
커맨드 라인에서 데이터를 다루는 것은 프로그래밍 언어를 사용하는 것과 다르며, 따라서 다른 사고방식이 필요합니다.

또한, 커맨드 라인 도구들 자체에도 독특한 특징이나 불일치하는 부분이 있습니다.
이는 부분적으로 이 도구들이 수십 년에 걸쳐 수많은 사람에 의해 개발되었기 때문입니다.
혹시라도 그 수많은 옵션에 대해 당황하게 된다면, 잊지 말고 `--help`, `man`, `tldr` 또는 자주 사용하는 검색 엔진을 활용해 보세요.

여전히, 특히 처음에는 좌절감을 느낄 수 있습니다.
저를 믿으세요, 커맨드 라인과 그 도구들을 사용하는 연습을 하다 보면 점점 더 능숙해질 것입니다.
커맨드 라인은 수십 년 동안 존재해 왔으며, 앞으로도 수십 년 동안 계속 존재할 것입니다.
그것은 투자할 가치가 충분합니다.


### 창의적이 되십시오

그와 관련된 두 번째 조언은 창의적이 되라는 것입니다.
커맨드 라인은 매우 유연합니다.
커맨드 라인 도구들을 결합함으로써, 여러분이 생각하는 것보다 더 많은 일을 해낼 수 있습니다.

저는 여러분이 즉시 프로그래밍 언어로 되돌아가지 않기를 권장합니다.
그리고 프로그래밍 언어를 사용해야 할 때는, 그 코드가 어떤 방식으로든 일반화되거나 재사용될 수 있을지 생각해 보세요.
만약 그렇다면 [4장](#chapter-4-creating-command-line-tools)에서 논의한 단계들을 따라 그 코드로 여러분만의 커맨드 라인 도구를 만드는 것을 고려해 보세요.
여러분의 도구가 다른 사람들에게도 유익할 것이라고 믿는다면 오픈 소스로 만드는 한 걸음을 더 나아갈 수도 있습니다.
커맨드 라인에서 수행하는 방법을 알고 있는 단계가 있지만, 현재 작업 중인 주요 프로그래밍 언어나 환경의 편안함을 떠나고 싶지 않을 수도 있습니다.
그럴 때는 [10장](#chapter-10-polyglot-data-science)에 나열된 접근 방식 중 하나를 사용할 수도 있습니다.


### 실용적이 되십시오

세 번째 조언은 실용적이 되라는 것입니다.
실용적이 되는 것은 창의적이 되는 것과 관련이 있지만, 별도의 설명이 필요합니다.
이전 하위 섹션에서 저는 즉시 프로그래밍 언어로 되돌아가지 말라고 언급했습니다.
물론 커맨드 라인에도 한계는 있습니다.
책 전반에 걸쳐 저는 커맨드 라인이 데이터 과학을 수행하는 데 있어 보조적인(companion) 접근 방식으로 간주되어야 한다고 강조해 왔습니다.

저는 커맨드 라인에서 데이터 과학을 수행하기 위한 네 단계를 논의했습니다.
실제로 커맨드 라인의 적용 가능성은 1단계가 4단계보다 더 높습니다.
여러분은 당면한 작업에 가장 잘 맞는 접근 방식을 사용해야 합니다.
그리고 워크플로우의 어느 지점에서든 접근 방식들을 혼합하여 사용하는 것도 완벽하게 괜찮습니다.
[10장](#chapter-10-polyglot-data-science)에서 보여드렸듯이, 커맨드 라인은 다른 접근 방식, 프로그래밍 언어, 통계 환경과 통합되는 데 매우 훌륭합니다.
각 접근 방식에는 일정한 트레이드오프(trade-off)가 있으며, 커맨드 라인에 능숙해지는 과정 중 일부는 언제 어떤 방식을 사용할지 배우는 것입니다.

결론적으로, 여러분이 인내심을 갖고 창의적이며 실용적이 될 때, 커맨드 라인은 여러분을 더 효율적이고 생산적인 데이터 과학자로 만들어 줄 것입니다.


## 앞으로 어디로 나아가야 할까요?

이 책은 커맨드 라인과 데이터 과학의 접점에 관한 것이므로, 많은 관련 주제가 맛보기로만 다루어졌습니다.
이제 이러한 주제들을 더 깊이 탐구하는 것은 여러분의 몫입니다.
다음 하위 섹션들은 참고할 만한 주제 리스트와 권장 자료들을 제공합니다.


## 커맨드 라인

- *The Linux Command Line: A Complete Introduction, 2nd Edition* By William E. Shotts, Jr. (No Starch Press, 2019)
- *Unix Power Tools, 3rd Edition* by Jerry Peek, Shelley Powers, Tim O'Reilly, and Mike Loukides (O'Reilly Media, 2002)
- *Learning the Vi and Vim Editors, 7th Edition* by Arnold Robbins, Elbert Hannah, and Linda Lamb (O'Reilly Media, 2008)


### 쉘 프로그래밍

- *Classic Shell Scripting* by Arnold Robbins and Nelson H.F. Beebe (O'Reilly Media, 2005)
- *Wicked Cool Shell Scripts, 2nd Edition* by Dave Taylor and Brandon Perry (No Starch Press, 2017)
- *Bash Cookbook* by Carl Albing JP Vossen (O'Reilly Media, 2018)


### Python, R, 그리고 SQL

- *Learn Python 3 the Hard Way* by Zed A. Shaw (Addison-Wesley Professional, 2017)
- *Python for Data Analysis, 2nd Edition* by Wes McKinney (O'Reilly Media, 2017)
- *Data Science from Scratch, 2nd Edition* by Joel Grus (O'Reilly Media, 2019)
- *R for Data Science* by Garrett Grolemund and Hadley Wickham (O'Reilly Media, 2016)
- *R for Everyone, 2nd edition* by Jared Lander  (Addison-Wesley Professional, 2017)
- *Sams Teach Yourself SQL in 10 Minutes a Day, 5th Edition* by Ben Forta (Sams, 2020)


### API

- *Mining the Social Web, 3rd Edition* by Matthew A. Russell and Mikhail Klassen (O'Reilly Media, 2019)
- *Data Source Handbook* by Pete Warden (O'Reilly Media, 2011)


### 머신러닝

- *Python Machine Learning, 3rd Edition* by Sebastian Raschka and Vahid Mirjalili (Packt Publishing, 2019)
- *Pattern Recognition and Machine Learning* by Christopher M. Bishop (Springer, 2006)
- *Information Theory, Inference, and Learning Algorithms* by David MacKay (Cambridge University Press, 2003)


## 연락하기

이 책은 커맨드 라인과 수많은 도구를 만든 많은 사람이 없었다면 세상에 나올 수 없었을 것입니다.
데이터 과학을 위한 현재의 커맨드 라인 도구 생태계는 커뮤니티의 노력의 결과라고 해도 과언이 아닙니다.
저는 여러분께 사용할 수 있는 수많은 커맨드 라인 도구 중 극히 일부만을 보여드릴 수 있었습니다.
새로운 도구들은 매일 만들어지고 있으며, 어쩌면 여러분도 언젠가 직접 도구를 만드실지도 모릅니다.
그런 경우, 여러분의 이야기를 듣고 싶습니다.
질문, 의견 또는 제안 사항이 있을 때 언제든지 연락해 주시면 감사하겠습니다.
저와 연락할 수 있는 몇 가지 방법은 다음과 같습니다.

- 이메일: <jeroen@jeroenjanssens.com>
- 트위터: [\@jeroenhjanssens](https://twitter.com/jeroenhjanssens/)
- 책 웹사이트: <https://datascienceatthecommandline.com/>
- 책 GitHub 저장소: <https://github.com/jeroenjanssens/data-science-at-the-command-line>

감사합니다.
