---
suppress-bibliography: true
---


<!--A[foreword]
A-->
# 서문 {-}

첫눈에 반했습니다.

1981년이나 1982년경에 처음으로 유닉스를 접했을 것입니다.
단일 명령과 복잡한 프로그램에 동일한 언어를 사용하는 명령줄 셸은 제 세상을 바꾸었고, 저는 결코 뒤돌아보지 않았습니다.

저는 컴퓨팅의 즐거움을 발견한 작가였고, 정규 표현식은 저의 입문 약물이었습니다.
HP의 RTE 운영 체제 텍스트 편집기에서 처음 시도했지만, 유닉스와 작은 협력 도구 철학, 그리고 그것들을 하나로 묶는 접착제로서의 명령줄 셸을 접하고 나서야 그 힘을 완전히 이해했습니다.
`ed`, `ex`, `vi`(현재 `vim`), `emacs`의 정규 표현식은 강력했지만, `ex` 스크립트가 유닉스 스트림 편집기인 `sed`가 되고, 그 다음 정규 표현식에 프로그래밍된 작업을 바인딩할 수 있는 AWK가 되고, 셸 스크립트를 통해 기존 도구뿐만 아니라 직접 작성한 새로운 도구로 파이프라인을 구축하는 방법을 보고 나서야 비로소 깨달았습니다.
프로그래밍은 컴퓨터와 대화하고, 컴퓨터에게 원하는 것을 말하는 방법이며, 한 번만이 아니라 인간 언어처럼 다양하게, 반복 가능한 구조와 다른 동사 및 객체를 사용하여 지속되는 방식으로 수행됩니다.

초보자로서 다른 형태의 프로그래밍은 정확히 따라야 하는 레시피, 모든 것을 올바르게 해야 하는 신중한 주문, 또는 선생님이 작성한 에세이를 채점하기를 기다리는 것과 같았습니다.
셸 프로그래밍에서는 컴파일과 기다림이 없었습니다.
친구와의 대화와 더 비슷했습니다.
친구가 이해하지 못하면 쉽게 다시 시도할 수 있었습니다.
게다가 간단하게 말할 것이 있으면 한 단어로 말할 수 있었습니다.
그리고 이미 말하고 싶은 많은 것들에 대한 단어가 있었습니다.
하지만 그렇지 않다면 쉽게 새로운 단어를 만들 수 있었습니다.
그리고 배운 단어와 만든 단어를 점차 더 복잡한 문장, 단락으로 엮어 결국 설득력 있는 에세이를 만들 수 있었습니다.

거의 모든 다른 프로그래밍 언어는 셸과 관련 도구보다 강력하지만, 적어도 저에게는 프로그래밍 사고방식으로 들어가는 더 쉬운 경로를 제공하는 언어는 없으며, 우리가 작업에 도움을 요청하는 기계와의 일상적인 대화를 위한 더 나은 환경을 제공하는 언어도 없습니다.
AWK의 제작자 중 한 명이자 훌륭한 책 *The Unix Programming Environment*의 공동 저자인 Brian Kernighan은 2019년 Lex Fridman과의 인터뷰에서 "[유닉스]는 프로그램을 작성하기 정말 쉬운 환경이 되도록 만들어졌습니다."라고 말했습니다. [[00:23:10]](https://www.happyscribe.com/public/lex-fridman-podcast-artificial-intelligence-ai/109-brian-kernighan-unix-c-awk-ampl-and-go-programming#paragraph_1371)
그는 데이터를 탐색할 때 Python 프로그램을 작성하는 대신 여전히 AWK를 자주 사용하는 이유를 설명했습니다.
"큰 프로그램에는 확장되지 않지만, 무언가에서 모든 것을 보고 싶을 때 이러한 작은 것들에서는 꽤 잘 작동합니다." [[00:37:01]](https://www.happyscribe.com/public/lex-fridman-podcast-artificial-intelligence-ai/109-brian-kernighan-unix-c-awk-ampl-and-go-programming#paragraph_2221)

*명령줄에서의 데이터 과학*에서 Jeroen Janssens는 유닉스/리눅스 방식의 명령줄이 오늘날에도 얼마나 강력한지 보여줍니다.
Jeroen이 이미 그렇게 하지 않았다면, 저는 명령줄이 데이터 과학에서 자주 접하는 종류의 작업과 왜 그렇게 달콤하고 강력한 조화를 이루는지에 대한 에세이를 여기에 썼을 것입니다.
하지만 그는 이미 책의 시작 부분에서 그것을 설명합니다.
그래서 저는 이렇게 말하겠습니다. 명령줄을 더 많이 사용할수록 많은 작업을 수행하는 가장 쉬운 방법으로 명령줄로 돌아오는 자신을 더 자주 발견하게 될 것입니다.
그리고 셸 초보자이든, 셸 프로그래밍이 데이터 과학에 얼마나 적합한지 별로 생각해 본 적이 없는 사람이든, 이 책은 소중히 여기게 될 책입니다.
Jeroen은 훌륭한 교사이며, 그가 다루는 자료는 매우 귀중합니다.

<p style="text-align: right; font-style: italic">
&mdash;Tim O'Reilly<br />
2021년 5월
</p>
