---
suppress-bibliography: true
---


<!--A[preface]
A-->
# 서문 {-}

데이터 과학은 흥미로운 작업 분야입니다.
또한 아직 비교적 젊습니다.
안타깝게도 많은 사람들, 그리고 많은 회사들도 데이터 과학이 제기하는 문제를 해결하기 위해 새로운 기술이 필요하다고 믿습니다.
그러나 이 책에서 보여주듯이, 명령줄을 사용하여 많은 것을 달성할 수 있으며 때로는 훨씬 더 효율적인 방식으로 달성할 수 있습니다.

박사 과정 중에 저는 점차 Microsoft Windows 사용에서 Linux 사용으로 전환했습니다.
처음에는 이 전환이 약간 무서웠기 때문에 두 운영 체제를 나란히 설치하는 것(듀얼 부팅이라고 함)부터 시작했습니다.
Microsoft Windows와 Linux를 번갈아 사용하려는 충동이 결국 사라졌고, 어느 시점에는 처음부터 자신만의 맞춤형 Linux 머신을 구축할 수 있는 Arch Linux를 만지작거리고 있었습니다.
명령줄만 주어지며, 그것으로 무엇을 만들지는 사용자에게 달려 있습니다.
필요에 따라 저는 빠르게 명령줄 사용에 매우 익숙해졌습니다.
결국 여가 시간이 더 소중해지면서 사용 편의성과 대규모 커뮤니티 때문에 Ubuntu로 알려진 Linux 배포판에 정착했습니다.
그러나 명령줄은 여전히 제가 가장 많은 시간을 보내는 곳입니다.

명령줄이 소프트웨어 설치, 시스템 구성 및 파일 검색만을 위한 것이 아니라는 것을 깨달은 지는 그리 오래되지 않았습니다.
저는 `cut`, `sort`, `sed`와 같은 도구에 대해 배우기 시작했습니다.
이것들은 데이터를 입력으로 받아 무언가를 처리하고 결과를 출력하는 명령줄 도구의 예입니다.
Ubuntu에는 꽤 많은 도구가 함께 제공됩니다.
이러한 작은 도구들을 결합하는 것의 잠재력을 이해하자마자 저는 푹 빠졌습니다.

박사 학위를 받은 후 데이터 과학자가 되었을 때, 저는 이 접근 방식을 사용하여 가능한 한 많은 데이터 과학을 하고 싶었습니다.
`xml2json`, `jq`, `json2csv`를 포함한 몇 가지 새로운 오픈 소스 명령줄 도구 덕분에 웹사이트 스크래핑 및 많은 JSON 데이터 처리와 같은 작업에도 명령줄을 사용할 수 있었습니다.

2013년 9월, 저는 [데이터 과학을 위한 7가지 명령줄 도구](http://www.jeroenjanssens.com/2013/09/19/seven-command-line-tools-for-data-science.html)라는 제목의 블로그 게시물을 작성하기로 결정했습니다.
놀랍게도 이 블로그 게시물은 상당한 주목을 받았고 다른 명령줄 도구에 대한 많은 제안을 받았습니다.
이 블로그 게시물을 책으로 만들 수 있을지 궁금해지기 시작했습니다.
약 10개월 후, 많은 재능 있는 사람들(감사의 글 참조)의 도움으로 그 대답이 '예'라는 사실에 기뻤습니다.

제가 이 개인적인 이야기를 공유하는 것은 이 책이 어떻게 나오게 되었는지 알아야 한다고 생각해서가 아니라, 저도 명령줄에 대해 배워야 했다는 것을 알리고 싶기 때문입니다.
명령줄은 그래픽 사용자 인터페이스를 사용하는 것과 매우 다르기 때문에 처음에는 무섭게 보일 수 있습니다.
하지만 제가 배울 수 있다면 여러분도 배울 수 있습니다.
현재 운영 체제가 무엇이든, 현재 데이터를 어떻게 사용하든, 이 책을 읽고 나면 명령줄에서 데이터 과학을 할 수 있게 될 것입니다.
이미 명령줄에 익숙하거나 셸 스크립트로 꿈을 꾸고 있더라도 다음 데이터 과학 프로젝트에 사용할 몇 가지 흥미로운 트릭이나 명령줄 도구를 발견할 가능성이 있습니다.


## 이 책에서 무엇을 기대할 수 있습니까 {-}


이 책에서는 많은 데이터를 얻고, 정리하고, 탐색하고, 모델링할 것입니다.
이 책은 이러한 데이터 과학 작업을 _더 잘_ 수행하는 방법에 관한 것이 아닙니다.
예를 들어, 어떤 통계 테스트를 언제 적용해야 하는지 또는 데이터를 가장 잘 시각화하는 방법에 대해 설명하는 훌륭한 자료는 이미 많이 있습니다.
대신, 이 실용적인 책은 명령줄에서 이러한 데이터 과학 작업을 수행하는 방법을 알려줌으로써 여러분을 더 _효율적_이고 _생산적_으로 만드는 것을 목표로 합니다.

이 책에서는 90개가 넘는 명령줄 도구를 설명하지만, 가장 중요한 것은 도구 자체가 아닙니다.
일부 명령줄 도구는 오랫동안 사용되어 왔지만 다른 도구는 더 나은 도구로 대체될 것입니다.
이 글을 읽는 동안에도 새로운 명령줄 도구가 만들어지고 있습니다.
수년에 걸쳐 저는 많은 놀라운 명령줄 도구를 발견했습니다.
안타깝게도 그중 일부는 너무 늦게 발견되어 책에 포함되지 못했습니다.
요컨대, 명령줄 도구는 왔다가 사라집니다.
하지만 괜찮습니다.

가장 중요한 것은 도구, 파이프 및 데이터로 작업하는 기본 아이디어입니다.
대부분의 명령줄 도구는 한 가지 작업을 수행하며 잘 수행합니다.
이것은 책 전체에 여러 번 등장하는 Unix 철학의 일부입니다.
명령줄에 익숙해지고, 명령줄 도구를 결합하는 방법을 알고, 심지어 새로운 도구를 만들 수 있게 되면 귀중한 기술을 개발한 것입니다.


## 2판 변경 사항 {-}

기술 및 작업 방식으로서의 명령줄은 시대를 초월하지만 1판에서 논의된 일부 도구는 최신 도구로 대체되었거나(예: `csvkit`이 대부분 `xsv`로 대체됨) 개발자가 포기했거나(예: `drake`), 최적이 아닌 선택이었습니다(예: `weka`).
2014년 10월 1판이 출판된 이후 제 자신의 경험이나 독자들의 유용한 피드백을 통해 많은 것을 배웠습니다.
이 책은 두 주제의 교차점에 있기 때문에 상당히 틈새 시장이지만 데이터 과학 커뮤니티의 꾸준한 관심이 있으며, 이는 제가 거의 매일 받는 많은 긍정적인 메시지에서 분명하게 드러납니다.
1판을 업데이트하여 최소한 앞으로 5년 동안 책의 관련성을 유지하기를 바랍니다.
다음은 제가 변경한 내용의 일부 목록입니다.

* 가능한 한 `csvkit`을 `xsv`로 교체했습니다. `xsv`는 CSV 파일 작업에 훨씬 빠른 대안입니다.
* 2.2절과 3.2절에서는 VirtualBox 이미지를 Docker 이미지로 교체했습니다. Docker는 VirtualBox보다 격리된 환경을 실행하는 더 빠르고 가벼운 방법입니다.
* 이제 HTML 작업에 `scrape` 대신 `pup`을 사용합니다. `scrape`은 제가 직접 만든 Python 도구입니다. `pup`은 훨씬 빠르고 기능이 더 많으며 설치가 더 쉽습니다.
* [6장](#chapter-6-project-management-with-make)은 처음부터 다시 작성되었습니다. `drake` 대신 이제 `make`를 사용하여 프로젝트 관리를 수행합니다. `drake`는 더 이상 유지 관리되지 않으며 `make`는 훨씬 더 성숙하고 개발자들에게 매우 인기가 있습니다.
* `Rio`를 `rush`로 교체했습니다. `Rio`는 제가 직접 만든 투박한 Bash 스크립트입니다. `rush`는 명령줄에서 R을 사용하는 훨씬 더 안정적이고 유연한 방법인 R 패키지입니다.
* [9장](#chapter-9-modeling-data)에서는 Weka와 BigML을 Vowpal Wabbit(`vw`)으로 교체했습니다. Weka는 오래되었고 명령줄에서 사용하는 방식이 투박합니다. BigML은 더 이상 의존하고 싶지 않은 상용 API입니다. Vowpal Wabbit은 Yahoo!에서 개발되었고 현재 Microsoft에서 개발 중인 매우 성숙한 기계 학습 도구입니다.
* [10장](#chapter-10-polyglot-data-science)은 Python, R, Apache Spark를 포함한 기존 워크플로에 명령줄을 통합하는 것에 대한 완전히 새로운 장입니다. 1판에서는 명령줄을 기존 워크플로와 쉽게 통합할 수 있다고 언급했지만 자세히 설명하지는 않았습니다. 이 장에서는 이를 수정합니다.


## 이 책을 읽는 방법 {-}

일반적으로 이 책을 순서대로 읽는 것이 좋습니다.
개념이나 명령줄 도구가 소개되면 나중에 해당 장에서 사용할 가능성이 있습니다.
예를 들어, [9장](#chapter-9-modeling-data)에서는 [8장](#chapter-8-parallel-pipelines)에서 광범위하게 소개된 `parallel`을 많이 사용합니다.

데이터 과학은 프로그래밍, 데이터 시각화, 기계 학습과 같은 다른 많은 분야와 교차하는 광범위한 분야입니다.
결과적으로 이 책은 안타깝게도 자세히 설명할 수 없는 많은 흥미로운 주제를 다룹니다.
책 전체에 걸쳐 각 장의 끝에는 추가 탐색을 위한 제안이 있습니다.
책을 따라가는 데 이 자료를 읽을 필요는 없지만, 관심이 있다면 배울 것이 훨씬 더 많다는 것을 알게 될 것입니다.


## 이 책의 대상 독자 {-}


이 책은 여러분에 대해 단 한 가지 가정을 합니다. 즉, 여러분이 데이터를 다룬다는 것입니다.
현재 어떤 프로그래밍 언어나 통계 컴퓨팅 환경을 사용하고 있는지는 중요하지 않습니다.
이 책은 처음부터 필요한 모든 개념을 설명합니다.

운영 체제가 Microsoft Windows, macOS 또는 어떤 형태의 Linux인지도 중요하지 않습니다.
이 책에는 설치하기 쉬운 가상 환경인 Docker 이미지가 함께 제공됩니다.
이를 통해 이 책이 작성된 것과 동일한 환경에서 명령줄 도구를 실행하고 코드 예제를 따라 할 수 있습니다.
모든 명령줄 도구와 해당 종속성을 설치하는 방법을 알아내는 데 시간을 낭비할 필요가 없습니다.

이 책에는 Bash, Python, R 코드가 일부 포함되어 있으므로 프로그래밍 경험이 있으면 도움이 되지만 예제를 따라 하는 데 반드시 필요한 것은 아닙니다.


## 이 책에서 사용된 규칙 {-}

이 책에서는 다음과 같은 인쇄 규칙을 사용합니다.

*기울임꼴*

:   새로운 용어, URL, 디렉터리 이름 및 파일 이름을 나타냅니다.

`고정 폭`

:   코드 및 명령에 사용되며 단락 내에서 명령줄 도구 및 해당 옵션을 참조하는 데에도 사용됩니다.

**`고정 폭 굵게`**

:   사용자가 문자 그대로 입력해야 하는 명령 또는 기타 텍스트를 보여줍니다.



```{block2, type="rmdtip"}
이 요소는 팁이나 제안을 의미합니다.
```

```{block2, type="rmdnote"}
이 요소는 일반적인 메모를 의미합니다.
```

```{block2, type="rmdcaution"}
이 요소는 경고 또는 주의를 나타냅니다.
```

<!--A
=== 코드 예제 사용

보충 자료(코드 예제, 연습 문제 등)는 link:$$https://github.com/jeroenjanssens/data-science-at-the-command-line$$[]에서 다운로드할 수 있습니다.

이 책은 여러분의 작업을 완료하는 데 도움이 되도록 만들어졌습니다. 일반적으로 이 책에서 제공되는 예제 코드는 프로그램 및 설명서에 사용할 수 있습니다. 코드의 상당 부분을 복제하지 않는 한 허가를 받기 위해 저희에게 연락할 필요는 없습니다. 예를 들어 이 책의 여러 코드 조각을 사용하는 프로그램을 작성하는 데는 허가가 필요하지 않습니다. O'Reilly 책의 예제를 판매하거나 배포하는 데는 허가가 필요합니다. 이 책을 인용하고 예제 코드를 인용하여 질문에 답하는 데는 허가가 필요하지 않습니다. 이 책의 상당량의 예제 코드를 제품 설명서에 통합하는 데는 허가가 필요합니다.

저작자 표시는 감사하지만 일반적으로 요구하지는 않습니다. 저작자 표시에는 일반적으로 제목, 저자, 출판사 및 ISBN이 포함됩니다. 예를 들어 "Jeroen Janssens의 명령줄에서의 데이터 과학(O'Reilly). Copyright 2021 Jeroen Janssens, 978-1-492-08791-5."입니다.

코드 예제 사용이 공정 사용 또는 위에 제공된 허가를 벗어난다고 생각되면 언제든지 pass:[<a class="email" href="mailto:permissions@oreilly.com"><em>permissions@oreilly.com</em></a>]으로 문의하십시오.

=== O'Reilly 온라인 학습

[role = "ormenabled"]
[NOTE]
====
40년 이상 동안 pass:[<a href="http://oreilly.com" class="orm:hideurl"><em class="hyperlink">O’Reilly Media</em></a>]는 기업의 성공을 돕기 위해 기술 및 비즈니스 교육, 지식 및 통찰력을 제공해 왔습니다.
====

당사의 고유한 전문가 및 혁신가 네트워크는 책, 기사 및 온라인 학습 플랫폼을 통해 지식과 전문성을 공유합니다. O'Reilly의 온라인 학습 플랫폼은 실시간 교육 과정, 심층 학습 경로, 대화형 코딩 환경, O'Reilly 및 200개 이상의 다른 출판사의 방대한 텍스트 및 비디오 모음에 대한 주문형 액세스를 제공합니다. 자세한 내용은 pass:[<a href="http://oreilly.com" class="orm:hideurl"><em>http://oreilly.com</em></a>]을 방문하십시오.

=== 연락 방법

이 책에 대한 의견과 질문은 다음 출판사로 보내주십시오.

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (미국 또는 캐나다)</li>
  <li>707-829-0515 (국제 또는 현지)</li>
  <li>707-829-0104 (팩스)</li>
</ul>
++++

이 책에 대한 웹 페이지가 있으며 여기에는 정오표, 예제 및 추가 정보가 나열되어 있습니다. link:$$https://wwww.datascienceatthecommandline.com$$[]에서 이 페이지에 액세스할 수 있습니다.

이 책에 대한 의견이나 기술적인 질문은 pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>]으로 이메일을 보내주십시오.

당사 책 및 과정에 대한 뉴스와 정보는 link:$$http://oreilly.com$$[]을 방문하십시오.

Facebook에서 저희를 찾으십시오: link:$$http://facebook.com/oreilly$$[]

Twitter에서 저희를 팔로우하십시오: link:$$http://twitter.com/oreillymedia$$[]

YouTube에서 저희를 시청하십시오: link:$$http://www.youtube.com/oreillymedia$$[]



A-->


## 감사의 글 {-}


### 2판 감사의 글 (2021) {-}

1판이 나온 지 7년이 지났습니다.
이 기간 동안, 특히 지난 13개월 동안 많은 분들이 저를 도와주셨습니다.
그분들이 없었다면 2판을 쓸 수 없었을 것입니다.

O'Reilly에서 다시 한번 세 분의 훌륭한 편집자분들과 함께 일할 수 있는 축복을 받았습니다.
Sarah "마감일을 지켜라" Grey, Jess "최선을 다해" Haberman, Kate "내버려 둬" Galloway에게 감사드립니다. 그분들의 중간 이름이 모든 것을 말해줍니다. 그분들의 놀라운 도움으로 마감일을 지키고, 중요할 때 최선을 다하고, 결국에는 내버려 둘 수 있었습니다.
또한 Angela Rufino, Arthur Johnson, Cassandra Furtado, David Futato, Helen Monroe, Karen Montgomery, Kate Dullea, Kristen Brown, Marie Beaugureau, Marsee Henon, Nick Adams, Regina Wilkinson, Shannon Cutt, Shannon Turlington, Yasmina Greco 동료분들께도 O'Reilly와의 협업을 즐겁게 만들어 주셔서 감사드립니다.

코드 실행 및 결과 붙여넣기 자동화 프로세스(R Markdown 및 Docker 덕분에)에도 불구하고 제가 저지른 실수의 수는 인상적입니다.
Aaditya Maruthi, Brian Eoff, Caitlin Hudon, Julia Silge, Mike Dewar, Shane Reustle에게 이 수를 엄청나게 줄여주셔서 감사합니다.
물론 남은 실수는 모두 제 책임입니다.

Marc Canaleta에게 특별한 감사를 전합니다.
1판이 나온 직후인 2014년 10월, Marc는 바르셀로나 Social Point 팀에게 _명령줄에서의 데이터 과학_에 대한 하루 워크숍을 진행해 달라고 저를 초대했습니다.
우리 둘 다 많은 워크숍이 이어질 것이라는 것을 거의 알지 못했습니다.
결국 저는 제 회사인 Data Science Workshops를 시작하게 되었습니다.
가르칠 때마다 새로운 것을 배웁니다.
그분들은 모르시겠지만, 모든 학생이 어떤 식으로든 이 책에 영향을 미쳤습니다.
그분들께 감사드립니다.
오랫동안 가르칠 수 있기를 바랍니다.

매혹적인 대화, 훌륭한 제안, 열정적인 풀 리퀘스트.
다음 관대한 분들의 모든 기여에 진심으로 감사드립니다.
Adam Johnson,
Andre Manook,
Andrea Borruso,
Andres Lowrie,
Andrew Berisha,
Andrew Gallant,
Andrew Sanchez,
Anicet Ebou,
Anthony Egerton,
Ben Isenhart,
[.keep-together]#Chris Wiggins#,
Chrys Wu,
Dan Nguyen,
Darryl Amatsetam,
Dmitriy Rozhkov,
Doug Needham,
Edgar Manukyan,
Erik Swan,
Felienne Hermans,
George Kampolis,
Giel van Lankveld,
Greg Wilson,
Hay Kranen,
Ioannis Cherouvim,
Jake Hofman,
Jannes Muenchow,
Jared Lander,
Jay Roaf,
Jeffrey Perkel,
Jim Hester,
Joachim Hagege,
Joel Grus,
John Cook,
John Sandall,
Joost Helberg,
Joost van Dijk,
Joyce Robbins,
Julian Hatwell,
Karlo Guidoni,
Karthik Ram,
Lissa Hyacinth,
Longhow Lam,
Lui Pillmann,
Lukas Schmid,
Luke Reding,
Maarten van Gompel,
Martin Braun,
Max Schelker,
Max Shron,
Nathan Furnal,
Noah Chase,
Oscar Chic,
Paige Bailey,
Peter Saalbrink,
Rich Pauloo,
Richard Groot,
Rico Huijbers,
Rob Doherty,
Robbert van Vlijmen,
Russell Scudder,
Sylvain Lapoix,
TJ Lavelle,
Tan Long,
Thomas Stone,
Tim O'Reilly,
Vincent Warmerdam, and
Yihui Xie.

이 책 전체, 특히 각주와 부록에서 수백 개의 이름을 찾을 수 있습니다.
이 이름들은 이 책이 기반을 둔 많은 도구, 책 및 기타 자료의 저자들의 것입니다.
50년 전이든 50일 전이든 그들의 노고에 진심으로 감사합니다.

무엇보다도 매일 진정으로 중요한 것이 무엇인지 일깨워주는 아내 Esther, 딸 Florien, 아들 Olivier에게 감사드립니다.
3판을 쓰기 시작하기까지 몇 년이 걸릴 것이라고 약속합니다.


### 1판 감사의 글 (2014) {-}

먼저, 2013년 9월에 작성한 제 블로그 게시물 [데이터 과학을 위한 7가지 명령줄 도구](http://jeroenjanssens.com/2013/09/19/seven-command-line-tools-for-data-science.html)가 책으로 확장될 수 있다고 믿어준 Mike Dewar와 Mike Loukides에게 감사드립니다.

다양한 초안을 읽고, 모든 명령을 꼼꼼하게 테스트하고, 귀중한 피드백을 제공해 준 기술 검토자인 Mike Dewar, Brian Eoff, Shane Reustle에게 특별한 감사를 전합니다.
여러분의 노력으로 책이 크게 향상되었습니다.
나머지 오류는 전적으로 제 책임입니다.

Ann Spencer, Julie Steele, Marie Beaugureau라는 세 명의 훌륭한 편집자와 함께 일할 수 있는 특권을 누렸습니다.
여러분의 지도와 O'Reilly의 많은 재능 있는 사람들과의 훌륭한 연락책이 되어준 것에 감사드립니다.
그 사람들에는 Laura Baldwin, Huguette Barriere, Sophia DeMartini, Yasmina Greco, Rachel James, Ben Lorica, Mike Loukides, Christopher Pappas가 포함됩니다.
뒤에서 활동하고 있기 때문에 만나지 못한 다른 많은 사람들이 있습니다.
그들은 함께 O'Reilly와 함께 일하는 것이 정말 즐거웠다는 것을 보장했습니다.

이 책에서는 80개가 넘는 명령줄 도구를 설명합니다.
말할 필요도 없이 이러한 도구가 없었다면 이 책은 애초에 존재하지 않았을 것입니다.
따라서 이러한 도구를 만들고 기여한 모든 저자에게 매우 감사합니다.
안타깝게도 전체 저자 목록은 여기에 포함하기에는 너무 깁니다. 부록에 언급되어 있습니다.
특히 Aaron Crow, Jehiah Czebotar, Christoph Groskopf, Dima Kogan, Sergey Lisitsyn, Francisco J.
Martin, Ole Tange에게 놀라운 명령줄 도구에 대한 도움을 주신 것에 대해 감사드립니다.

박사 과정 동안 저를 지도해 주신 Eric Postma와 Jaap van den Herik에게 특별한 감사를 드립니다.
5년 동안 그들은 저에게 많은 교훈을 가르쳐 주었습니다.
기술 서적을 쓰는 것은 박사 학위 논문을 쓰는 것과는 상당히 다르지만, 그 교훈 중 많은 부분이 지난 9개월 동안에도 매우 도움이 되었습니다.

마지막으로, YPlan 동료, 친구, 가족, 특히 저를 지지해 주고 적절한 시기에 명령줄에서 저를 끌어내 준 아내 Esther에게 감사드립니다.
